import random
from datetime import date
from django.db import migrations

def add_expenses(apps, schema_editor):
    Expense = apps.get_model('webapp', 'Expense')
    Category = apps.get_model('webapp', 'Category')
    Currency = apps.get_model('webapp', 'Currency')

    # Retrieve the Australian Dollar currency from the database
    aud = Currency.objects.get(code="AUD")

    # Retrieve all categories
    categories = list(Category.objects.all())

    # Function to generate random expenses for given months and year
    def generate_expenses_for_month(year, month, num_expenses):
        expenses = []
        for _ in range(num_expenses):
            expense = Expense(
                category=random.choice(categories),
                currency=aud,
                amount=random.uniform(10.0, 500.0),  # Random expense between $10 and $500
                date=date(year, month, random.randint(1, 28 if month == 2 else 30)),  # Random day in the month
                description="Autogenerated expense"
            )
            expenses.append(expense)
        return expenses

    # Generate 50 random expenses for each month: January, February, March, April, May 2024
    expenses = (
        generate_expenses_for_month(2024, 1, 50) +
        generate_expenses_for_month(2024, 2, 50) +
        generate_expenses_for_month(2024, 3, 50) +
        generate_expenses_for_month(2024, 4, 50) +
        generate_expenses_for_month(2024, 5, 50)
    )

    Expense.objects.bulk_create(expenses)

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(add_expenses, reverse_code=migrations.RunPython.noop),
    ]