from django.db import migrations
import random
from datetime import date

def add_expenses(apps, schema_editor):
    Expense = apps.get_model('webapp', 'Expense')
    Category = apps.get_model('webapp', 'Category')
    Currency = apps.get_model('webapp', 'Currency')

    # Retrieve the Australian Dollar currency from the database
    aud = Currency.objects.get(code="AUD")

    # Retrieve all categories
    categories = list(Category.objects.all())

    # Generate 50 random expenses for April 2024
    expenses = []
    for _ in range(50):
        expense = Expense(
            category=random.choice(categories),
            currency=aud,
            amount=random.uniform(10.0, 2000.0),  # Random expense between $10 and $2000
            date=date(2024, 4, random.randint(1, 30)),  # Random day in April
            description="Autogenerated expense"
        )
        expenses.append(expense)

    Expense.objects.bulk_create(expenses)

class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0002_initial')
    ]

    operations = [
        migrations.RunPython(add_expenses),
    ]